dist: xenial
language: go
sudo: false
go:
  - 1.13.x
services:
  - redis
addons:
  apt:
    packages:
    - rabbitmq-server
before_install:
  - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
install:
  - go build
script:
  - golangci-lint run
  - go test -v -cover .
  - goveralls -service=travis-ci
