name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        go get -u github.com/golang/dep/cmd/dep
        dep ensure

    - name: Build
      run: go build -v .
      
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
        - 6379:6379
        options: --entrypoint redis-server
      rabbitmq:
        image: rabbitmq
        ports:
        - 5672:5672

    steps:
      - name: Test
        run: go test -v .

